### PR TITLE
Feat: Add custom database name support

### LINKED ISSUE #12: Support DB_NAME in the database link
Currently, we can select a database to link it to an instance. However, it is not possible to select the database (`DB_NAME`).

One way of supporting that in the "Vertex Containers" app should be to add a field to enter the database name. Later, the SQL app will also manage the creation of this database.

image

### PR DESCRIPTION
**Pull request by MinhDuongg**
Feat: Add custom database name support (fixes #12)
- Add DefaultDatabase In feature struct
- Add PatchBodyDatabase struct for PATCH operation supporting custom database_name (can add support alternate username and password )
- Support delete outdated env variable 
- Fix a bug in the write env file operation

### CODE REVIEW

**Review by quentinguidee — CHANGES_REQUESTED** [review]
Thanks a lot for this pull request! Really clean!

I have maybe one requests to improve this PR:

- I took some time to understand the `modifiedFeatures` variable when reading the `SetDatabases` method definition. Maybe simply call this variable `options`? As they are the options while calling SetDatabases. And the type of `options` could then be another type more specific, like `SetDatabasesOptions`, because for now we can give more parameters to the `DatabaseFeature` that the method will ignore.

Apart from this, that's really good work, thank you!!

**Comment by quentinguidee** [comment]
That's perfect, thank you! Did you manage to do the frontend part, or you prefer that I do it?

**Comment by MinhDuongg** [comment]
> That's perfect, thank you! Did you manage to do the frontend part, or you prefer that I do it?

Yes, I'm struggling with the frontend :)) I would be very grateful if you could help me with that part. Please tell me if anything is not clear.

**Comment by quentinguidee** [comment]
Client updated with https://github.com/vertex-center/vertex-webui/pull/17

Thanks again for your contribution!! 🚀

**Pull request merged**
